# Generated by Django 4.0.4 on 2022-05-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(help_text='Ingrese el Nombre del Director', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingres el Titulo de la Pelicula', max_length=40)),
                ('descripcion', models.TextField(help_text='Ingrese breve descripción de la Pelicula', max_length=150)),
                ('estreno', models.DateField(help_text='Fecha de Estreno de la Pelicula')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.directores')),
            ],
        ),
    ]
