# Generated by Django 4.0.4 on 2022-05-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_peliculos_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='descripcion',
            field=models.TextField(help_text='Ingrese breve descripción de la Pelicula', max_length=600),
        ),
    ]
