# Generated by Django 4.0.4 on 2022-05-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_peliculas_descripcion_alter_peliculas_estreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Fecha de Nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='directores',
            name='informacion',
            field=models.TextField(help_text='Ingrese información del Director', max_length=1000, null=True),
        ),
    ]
