# Generated by Django 4.0.4 on 2022-05-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_directores_fecha_nacimiento_directores_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='foto',
            field=models.ImageField(null=True, upload_to='directores/fotos/'),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='image',
            field=models.ImageField(null=True, upload_to='peliculas/imagenes'),
        ),
    ]
